// Code generated by counterfeiter. DO NOT EDIT.
package routingapifakes

import (
	"context"
	"sync"

	"golang.org/x/oauth2"
)

type FakeUaaClient struct {
	FetchTokenStub        func(context.Context, bool) (*oauth2.Token, error)
	fetchTokenMutex       sync.RWMutex
	fetchTokenArgsForCall []struct {
		arg1 context.Context
		arg2 bool
	}
	fetchTokenReturns struct {
		result1 *oauth2.Token
		result2 error
	}
	fetchTokenReturnsOnCall map[int]struct {
		result1 *oauth2.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUaaClient) FetchToken(arg1 context.Context, arg2 bool) (*oauth2.Token, error) {
	fake.fetchTokenMutex.Lock()
	ret, specificReturn := fake.fetchTokenReturnsOnCall[len(fake.fetchTokenArgsForCall)]
	fake.fetchTokenArgsForCall = append(fake.fetchTokenArgsForCall, struct {
		arg1 context.Context
		arg2 bool
	}{arg1, arg2})
	stub := fake.FetchTokenStub
	fakeReturns := fake.fetchTokenReturns
	fake.recordInvocation("FetchToken", []interface{}{arg1, arg2})
	fake.fetchTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUaaClient) FetchTokenCallCount() int {
	fake.fetchTokenMutex.RLock()
	defer fake.fetchTokenMutex.RUnlock()
	return len(fake.fetchTokenArgsForCall)
}

func (fake *FakeUaaClient) FetchTokenCalls(stub func(context.Context, bool) (*oauth2.Token, error)) {
	fake.fetchTokenMutex.Lock()
	defer fake.fetchTokenMutex.Unlock()
	fake.FetchTokenStub = stub
}

func (fake *FakeUaaClient) FetchTokenArgsForCall(i int) (context.Context, bool) {
	fake.fetchTokenMutex.RLock()
	defer fake.fetchTokenMutex.RUnlock()
	argsForCall := fake.fetchTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUaaClient) FetchTokenReturns(result1 *oauth2.Token, result2 error) {
	fake.fetchTokenMutex.Lock()
	defer fake.fetchTokenMutex.Unlock()
	fake.FetchTokenStub = nil
	fake.fetchTokenReturns = struct {
		result1 *oauth2.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeUaaClient) FetchTokenReturnsOnCall(i int, result1 *oauth2.Token, result2 error) {
	fake.fetchTokenMutex.Lock()
	defer fake.fetchTokenMutex.Unlock()
	fake.FetchTokenStub = nil
	if fake.fetchTokenReturnsOnCall == nil {
		fake.fetchTokenReturnsOnCall = make(map[int]struct {
			result1 *oauth2.Token
			result2 error
		})
	}
	fake.fetchTokenReturnsOnCall[i] = struct {
		result1 *oauth2.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeUaaClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchTokenMutex.RLock()
	defer fake.fetchTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUaaClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
